/**
 * Created by wanpeng on 2017/2/17.
 */
export const ADD_PUBLISH = "ADD_PUBLISH"
export const UPDATE_PUBLISH = "UPDATE_PUBLISH"

export const UPDATE_PUBLISHES = "UPDATE_PUBLISHES"

export const FETCH_PUBLISHES = "FETCH_PUBLISHES"

export const PUBLISH_COMMENT_SUCCESS = "PUBLISH_COMMENT_SUCCESS"

export const PUBLISH_UPDATE_COMMENTCNT = "PUBLISH_UPDATE_COMMENTCNT"

export const UPDATE_PUBLISH_COMMENTS = "UPDATE_PUBLISH_COMMENTS"

export const UPDATE_PUBLISH_STATUS = "UPDATE_PUBLISH_STATUS"

export const UPDATE_PUBLISH_REFRESHTIME = "UPDATE_PUBLISH_REFRESHTIME"

export const FAVORITE_PUBLISH = "FAVORITE_PUBLISH"

export const UNFAVORITE_PUBLISH = "UNFAVORITE_PUBLISH"


