/**
 * Created by wanpeng on 2017/2/17.
 */
export const ADD_PUBLISH = "ADD_PUBLISH"
export const UPDATE_PUBLISH = "UPDATE_PUBLISH"

export const UPDATE_PUBLISHES = "UPDATE_PUBLISHES"

export const FETCH_LAST_PUBLISHES = "FETCH_LAST_PUBLISHES"

export const PUBLISH_COMMENT_SUCCESS = "PUBLISH_COMMENT_SUCCESS"

